/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Lucas Santos
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jbnAluguel = new javax.swing.JMenuItem();
        jbnCliente = new javax.swing.JMenuItem();
        jbnJogos = new javax.swing.JMenuItem();
        jbnConsole = new javax.swing.JMenuItem();
        jbnTipoConsole = new javax.swing.JMenuItem();
        jbnConta = new javax.swing.JMenuItem();
        jbnTipoConta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu2.setText("Cadastrar");

        jbnAluguel.setText("Aluguel");
        jbnAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnAluguelActionPerformed(evt);
            }
        });
        jMenu2.add(jbnAluguel);

        jbnCliente.setText("Cliente");
        jbnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnClienteActionPerformed(evt);
            }
        });
        jMenu2.add(jbnCliente);

        jbnJogos.setText("Jogos");
        jbnJogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnJogosActionPerformed(evt);
            }
        });
        jMenu2.add(jbnJogos);

        jbnConsole.setText("Console");
        jbnConsole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnConsoleActionPerformed(evt);
            }
        });
        jMenu2.add(jbnConsole);

        jbnTipoConsole.setText("Tipo Console");
        jbnTipoConsole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnTipoConsoleActionPerformed(evt);
            }
        });
        jMenu2.add(jbnTipoConsole);

        jbnConta.setText("Conta");
        jbnConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnContaActionPerformed(evt);
            }
        });
        jMenu2.add(jbnConta);

        jbnTipoConta.setText("Tipo Conta");
        jbnTipoConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnTipoContaActionPerformed(evt);
            }
        });
        jMenu2.add(jbnTipoConta);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        setBounds(0, 0, 619, 530);
    }// </editor-fold>//GEN-END:initComponents

    private void jbnJogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnJogosActionPerformed
        // TODO add your handling code here:
        TelaCadastroJogos telajogo = new TelaCadastroJogos();
        telajogo.setVisible(true);
    }//GEN-LAST:event_jbnJogosActionPerformed

    private void jbnContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnContaActionPerformed
        // TODO add your handling code here:
        TelaCadastroConta telaconta = new TelaCadastroConta();
        telaconta.setVisible(true);
    }//GEN-LAST:event_jbnContaActionPerformed

    private void jbnTipoConsoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnTipoConsoleActionPerformed
        // TODO add your handling code here:
        TelaCadastroTipoConsole telatpcon = new TelaCadastroTipoConsole();
        telatpcon.setVisible(true);
    }//GEN-LAST:event_jbnTipoConsoleActionPerformed

    private void jbnAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnAluguelActionPerformed
        // TODO add your handling code here:
        TelaCadastroAluguel telacad = new TelaCadastroAluguel();
        telacad.setVisible(true);
    }//GEN-LAST:event_jbnAluguelActionPerformed

    private void jbnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnClienteActionPerformed
        // TODO add your handling code here:
        TelaCadastroCliente telacli = new TelaCadastroCliente();
        telacli.setVisible(true);
    }//GEN-LAST:event_jbnClienteActionPerformed

    private void jbnTipoContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnTipoContaActionPerformed
        // TODO add your handling code here:
        TelaCadastroTipoConsole telatpconta = new TelaCadastroTipoConsole();
        telatpconta.setVisible(true);
    }//GEN-LAST:event_jbnTipoContaActionPerformed

    private void jbnConsoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnConsoleActionPerformed
        // TODO add your handling code here:
        TelaCadastroConsole telacon = new TelaCadastroConsole();
        telacon.setVisible(true);
    }//GEN-LAST:event_jbnConsoleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jbnAluguel;
    private javax.swing.JMenuItem jbnCliente;
    private javax.swing.JMenuItem jbnConsole;
    private javax.swing.JMenuItem jbnConta;
    private javax.swing.JMenuItem jbnJogos;
    private javax.swing.JMenuItem jbnTipoConsole;
    private javax.swing.JMenuItem jbnTipoConta;
    // End of variables declaration//GEN-END:variables
}
