/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Telefone;
import model.dao.ClienteDAO;
import model.dao.TelefoneDAO;

/**
 *
 * @author Bruno
 */
public class TelaCadastroTelefone extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroTelefone
     */
    public TelaCadastroTelefone() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        readJTable();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtCodArea = new javax.swing.JTextField();
        jbCadastrar = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtNumero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelTelefone = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Telefone");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtCodArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCodAreaActionPerformed(evt);
            }
        });
        getContentPane().add(jtCodArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 22, 71, -1));

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jbAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 100, -1, -1));

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jbExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 100, -1, -1));

        jLabel1.setText("CodArea");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, -1, -1));

        jLabel2.setText("Número");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, -1, -1));
        getContentPane().add(jtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 48, 136, -1));

        jLabel3.setText("Cliente");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, -1, -1));
        getContentPane().add(jtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 74, 136, -1));

        jTabelTelefone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "CodigoArea", "Número"
            }
        ));
        jTabelTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelTelefoneMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabelTelefone);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 510, 170));

        setSize(new java.awt.Dimension(507, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void readJTable() {
        DefaultTableModel modelo;
        modelo = (DefaultTableModel) jTabelTelefone.getModel();
        modelo.setNumRows(0);
        TelefoneDAO telefonedao = new TelefoneDAO();
        
        for (Telefone tc: telefonedao.read()) {
            modelo.addRow(new Object[] {
               tc,
               tc.getCodArea(),
               tc.getNumero()
            });
        }
    }
                                          

    private void jtCodAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCodAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCodAreaActionPerformed

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        // TODO add your handling code here:
        Telefone tel = new Telefone();
        TelefoneDAO dao = new TelefoneDAO();
        ClienteDAO cdao = new ClienteDAO();
        tel.setCliente(cdao.search(Integer.parseInt(jtCliente.getText())));
        tel.setCodArea(Integer.parseInt(jtCodArea.getText()));
        tel.setNumero(Long.parseLong((jtNumero.getText())));
        dao.create(tel);
        readJTable();
        
        jtCliente.setText("");
        jtCodArea.setText("");
        jtNumero.setText("");
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        // TODO add your handling code here:
        if(jTabelTelefone.getSelectedRow() != -1){
            Telefone tel = new Telefone();
            TelefoneDAO dao = new TelefoneDAO();
            ClienteDAO cdao = new ClienteDAO();
            tel.setCodArea(Integer.parseInt(jtCodArea.getText()));
            tel.setNumero(Integer.parseInt((jtNumero.getText())));
            tel.setCliente(cdao.search(Integer.parseInt(jtCliente.getText())));
            tel.setId(Integer.parseInt(jTabelTelefone.getValueAt(jTabelTelefone.getSelectedRow(), 0).toString()));
            dao.update(tel);
            
            jtCodArea.setText("");
            jtNumero.setText("");
            jtCliente.setText("");
            
            readJTable();
            
        }
            
        
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // TODO add your handling code here:
        if (jTabelTelefone.getSelectedRow() != -1){
            Telefone tel = new Telefone();
            TelefoneDAO dao = new TelefoneDAO();
            
            tel = dao.search(Integer.parseInt(jTabelTelefone.getValueAt(jTabelTelefone.getSelectedRow(), 0).toString()));
            dao.delete(tel);
            
            jtCodArea.setText("");
            jtNumero.setText("");
            jtCliente.setText("");
            
            readJTable();
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um telefone para Excluir!");
        }
        
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jTabelTelefoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelTelefoneMouseClicked
        // TODO add your handling code here:
        int row = jTabelTelefone.getSelectedRow();
        if (row != -1) {
            TelefoneDAO dao = new TelefoneDAO();
            Telefone tel = dao.search(Integer.parseInt(jTabelTelefone.getValueAt(row, 0).toString()));
            jtCodArea.setText(jTabelTelefone.getValueAt(row, 1).toString());
            jtNumero.setText(jTabelTelefone.getValueAt(row, 2).toString());
            jtCliente.setText(String.valueOf(tel.getCliente().getId()));
            
        }
    }//GEN-LAST:event_jTabelTelefoneMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTelefone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTelefone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTelefone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTelefone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroTelefone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabelTelefone;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JTextField jtCliente;
    private javax.swing.JTextField jtCodArea;
    private javax.swing.JTextField jtNumero;
    // End of variables declaration//GEN-END:variables
}
